name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # 可以根据你的项目需求修改 Node.js 版本
      - name: Install dependencies
        run: |
          npm install
      - name: Build Vue project
        run: |
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
